--- 
development: 
  adapter: jdbcmysql
  database: amivoice_operators_help_acss
  host: 192.168.1.15
  port: 3306
  username: mysqladmin
  password: password
  encoding: utf8
production: 
  adapter: jdbcmysql
  database: amivoice_operators_help_acss
  host: 192.168.1.15
  port: 3306
  username: mysqladmin
  password: password
  encoding: utf8
test: 
  adapter: jdbcmysql
  database: amivoice_operators_help_acss_v2
  host: 192.168.1.15
  port: 3306
  username: mysqladmin
  password: password
  encoding: utf8
